// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package usersdb

import (
	"database/sql"
)

type User struct {
	ID        int32
	Name      string
	Email     string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
