// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package usersdb

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeleteUser(ctx context.Context, id int32) (DeleteUserRow, error)
	UpdateUserName(ctx context.Context, arg UpdateUserNameParams) error
}

var _ Querier = (*Queries)(nil)
