// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: exec.sql

package paymentsdb

import (
	"context"
	"database/sql"
	"time"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (invoice_id, amount_cents,status ) values($1,$2,$3)
RETURNING invoice_id,amount_cents,status,updated_at
`

type CreatePaymentParams struct {
	InvoiceID   string
	AmountCents int32
	Status      sql.NullString
}

type CreatePaymentRow struct {
	InvoiceID   string
	AmountCents int32
	Status      sql.NullString
	UpdatedAt   time.Time
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (CreatePaymentRow, error) {
	row := q.db.QueryRowContext(ctx, createPayment, arg.InvoiceID, arg.AmountCents, arg.Status)
	var i CreatePaymentRow
	err := row.Scan(
		&i.InvoiceID,
		&i.AmountCents,
		&i.Status,
		&i.UpdatedAt,
	)
	return i, err
}

const setPaymentStatus = `-- name: SetPaymentStatus :one
UPDATE payments set status = $1, updated_at = CURRENT_TIMESTAMP where id = $2
RETURNING id, invoice_id, amount_cents, status, updated_at
`

type SetPaymentStatusParams struct {
	Status sql.NullString
	ID     int32
}

func (q *Queries) SetPaymentStatus(ctx context.Context, arg SetPaymentStatusParams) (Payment, error) {
	row := q.db.QueryRowContext(ctx, setPaymentStatus, arg.Status, arg.ID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.AmountCents,
		&i.Status,
		&i.UpdatedAt,
	)
	return i, err
}
