// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package paymentsdb

import (
	"database/sql"
	"time"
)

type Payment struct {
	ID          int32
	InvoiceID   string
	AmountCents int32
	Status      sql.NullString
	UpdatedAt   time.Time
}
