// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package paymentsdb

import (
	"context"
)

type Querier interface {
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (CreatePaymentRow, error)
	SetPaymentStatus(ctx context.Context, arg SetPaymentStatusParams) (Payment, error)
}

var _ Querier = (*Queries)(nil)
