// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: exec.sql

package productsdb

import (
	"context"
	"database/sql"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (name, status, price)
VALUES ($1, $2, $3)
RETURNING id, name, price, status, created_at, updated_at
`

type CreateProductParams struct {
	Name   string
	Status string
	Price  sql.NullInt32
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, createProduct, arg.Name, arg.Status, arg.Price)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :execrows
DELETE from products where name = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, name string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteProduct, name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
