// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package productsdb

import (
	"database/sql"
)

type Product struct {
	ID        int32
	Name      string
	Price     sql.NullInt32
	Status    string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
