// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package productsdb

import (
	"time"
)

type Product struct {
	ID          int32
	Slug        string
	Title       string
	Description string
	PriceCents  int32
	CreatedAt   time.Time
}
