// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package productsdb

import (
	"context"
)

type Querier interface {
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	DeleteAllProducts(ctx context.Context) error
	DeleteProduct(ctx context.Context, id int32) (int64, error)
	GetProductByID(ctx context.Context, id int32) (Product, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error)
	UpdateProductPrice(ctx context.Context, arg UpdateProductPriceParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
