// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Product struct {
	ID        int32
	Name      string
	Price     int32
	Status    string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type User struct {
	ID        int32
	Name      string
	Email     string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
